- name: Install abinit test dependencies
  become: true
  apt:
    name:
    - ssh

- name: Create python testing venv
  import_role:
    name: marvel-nccr.python
  vars:
    python_base_version: '3.7'
    python_venv_path: /tmp/abinit_test_venv
    python_venv_state: present
    python_venv_packages:
    - numpy==1.19.4
    - pandas==1.1.4
    - pyyaml==5.3.1

- name: Read test pass indicator
  stat:
    path: "{{ abinit_code_folder }}/{{ abinit_src }}/tests/TESTS_PASSED"
  register: abinit_tests_passed

- name: run the tests ({{ abinit_build_cpus }} cpu)
  when: abinit_make.changed or (not abinit_tests_passed.stat.exists)
  shell: >
    /tmp/abinit_test_venv/bin/python runtests.py --build-tree="{{ abinit_code_folder }}/{{ abinit_src }}/build" -j {{ abinit_build_cpus }} {{ item }}
  args:
    chdir: "{{ abinit_code_folder }}/{{ abinit_src }}/tests"
  register: abinit_test
  until: not abinit_test.failed
  retries: 2
  delay: 1
  loop: "{{ abinit_tests }}"

- name: Write test pass indicator
  file:
    path: "{{ abinit_code_folder }}/{{ abinit_src }}/tests/TESTS_PASSED"
    state: touch
    modification_time: preserve
    access_time: preserve
