- name: Install abinit test dependencies
  become: true
  apt:
    name:
    - ssh

- name: Create python testing venv
  import_role:
    name: marvel-nccr.python
  vars:
    python_base_version: '3.7'
    python_venv_path: /tmp/abinit_test_venv
    python_venv_packages:
    - numpy
    - pandas
    - pyyaml

- name: run the tests ({{ abinit_build_cpus }} cpu)
  shell: /tmp/abinit_test_venv/bin/python runtests.py --build-tree="{{ abinit_code_folder }}/{{ abinit_src }}/build" -j {{ abinit_build_cpus }} {{ item }}
  args:
    chdir: "{{ abinit_code_folder }}/{{ abinit_src }}/tests"
  register: abinit_test
  until: not abinit_test.failed
  retries: 2
  delay: 1
  loop: "{{ abinit_tests }}"
  changed_when: false
