- name: Install tox
  pip:
    name: tox

- name: Create the tox.ini
  template:
    src: tox.ini.j2
    dest: "{{ abinit_code_folder }}/{{ abinit_src }}/config_options.sh"

- name: run the tests ({{ abinit_build_cpus }} cpu)
  shell: tox {{ item }} -- -j {{ abinit_build_cpus }}
  args:
    chdir: "{{ abinit_code_folder }}/{{ abinit_src }}/tests"
  with_items: "{{ abinit_tests }}"
  changed_when: false
