- name: Install abinit test dependencies
  become: true
  apt:
    name:
    - libyaml-dev
    - python3-dev
    - python3-pip
    - ssh

- name: Install tox
  pip:
    name: tox

- name: Create the tox.ini
  template:
    src: tox.ini.j2
    dest: "{{ abinit_code_folder }}/{{ abinit_src }}/tests/tox.ini"

- name: run the tests ({{ abinit_build_cpus }} cpu)
  shell: tox {{ item }} -- -j {{ abinit_build_cpus }}
  args:
    chdir: "{{ abinit_code_folder }}/{{ abinit_src }}/tests"
  register: abinit_test
  until: not abinit_test.failed
  retries: 2
  delay: 1
  loop: "{{ abinit_tests }}"
  changed_when: false
