- name: Converge
  hosts: all

  pre_tasks:
  - name: Update apt cache.
    apt:
      update_cache: yes
      cache_valid_time: 36000
    when: ansible_os_family|lower == 'debian'

  vars:
    run_tests: true
    ansible_python_interpreter: /usr/bin/python3
    libxc_version: "4.3.4"
    libxc_prefix: "/usr/local/libxc-{{ libxc_version }}"

  roles:
  - role: marvel-nccr.libxc
  - role: marvel-nccr.abinit
    vars:
      abinit_libxc_path: "{{ libxc_prefix }}"
