- name: Converge
  hosts: all

  pre_tasks:
  - name: Update apt cache.
    apt:
      update_cache: yes
      cache_valid_time: 6000
    when: ansible_os_family|lower == 'debian'

  vars:
    run_tests: true
    ansible_python_interpreter: /usr/bin/python3

  roles:
  - role: marvel-nccr.abinit
