- name: Converge
  hosts: all

  pre_tasks:
  - name: Update apt cache.
    apt:
      update_cache: yes
      cache_valid_time: 36000
    when: ansible_os_family|lower == 'debian'

  vars:
    libxc_version: "4.3.4"
    libxc_prefix: "/usr/local/libxc-{{ libxc_version }}"

  tasks:
  - include_role:
      name: marvel-nccr.libxc
    when: test_libxc|bool
  - include_role:
      name: marvel-nccr.abinit
    when: test_libxc|bool
    vars:
      abinit_libxc_path: "{{ libxc_prefix }}"
  - include_role:
      name: marvel-nccr.abinit
    when: not test_libxc|bool
